import {Component, OnInit, ViewChild} from '@angular/core';
import {Router} from '@angular/router';
import {Image} from '../../models/image';
import {Track} from '../../models/track';
import {Playlist} from '../../models/playlist';
import {SpotifyService} from "../../services/spotify.service";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  playlist: Playlist;
  tracks: Array<Track>;

  @ViewChild('loginComponent') loginComponent;


  constructor(private router: Router, private spotifyService: SpotifyService) {}

  ngOnInit(): void {
    this.playlist = mockPlaylist;
    this.tracks = tracks;

  }

  login(): void {
    this.router.navigate((['login']));
  }
  check(): void{
  }

}

let mockPlaylist;

const mockPlaylistData = {
  name: '😴',
  images: [{
    height: null,
    url: 'https://i.scdn.co/image/ab67706c0000bebbb02e1e7f393323ff7cffe409',
    width: null
  }],
  tracks: {
    href: 'https://api.spotify.com/v1/playlists/6h5LVYdbXaFCK7BdttuF3P/tracks',
    total: 63
  }
};
const image = new Image();
image.height = 640;
image.url = 'https://i.scdn.co/image/ab67706c0000bebbb02e1e7f393323ff7cffe409';
image.width = 640;



const tracks = [
  {
    name: 'Sober',
    preview: 'https://p.scdn.co/mp3-preview/b176ed71e628bbbb7f96c9aa4be74d53b8375052?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
    popularity: 72,
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/73sIBHcqh3Z3NyqHKZ7FOL'
        },
        href: 'https://api.spotify.com/v1/artists/73sIBHcqh3Z3NyqHKZ7FOL',
        id: '73sIBHcqh3Z3NyqHKZ7FOL',
        name: 'Childish Gambino',
        type: 'artist',
        uri: 'spotify:artist:73sIBHcqh3Z3NyqHKZ7FOL'
      }
    ],
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/73sIBHcqh3Z3NyqHKZ7FOL'
          },
          href: 'https://api.spotify.com/v1/artists/73sIBHcqh3Z3NyqHKZ7FOL',
          id: '73sIBHcqh3Z3NyqHKZ7FOL',
          name: 'Childish Gambino',
          type: 'artist',
          uri: 'spotify:artist:73sIBHcqh3Z3NyqHKZ7FOL'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MV',
        'MW',
        'MX',
        'MY',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZW'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1gN7MUuz99VAKnB58U1aZy'
      },
      href: 'https://api.spotify.com/v1/albums/1gN7MUuz99VAKnB58U1aZy',
      id: '1gN7MUuz99VAKnB58U1aZy',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b2737206597364af87adb3377b0e',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e027206597364af87adb3377b0e',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d000048517206597364af87adb3377b0e',
          width: 64
        }
      ],
      name: 'Kauai',
      release_date: '2014-10-03',
      release_date_precision: 'day',
      total_tracks: 7,
      type: 'album',
      uri: 'spotify:album:1gN7MUuz99VAKnB58U1aZy'
    },
    image: {
      url: 'https://i.scdn.co/image/ab67616d0000b2737206597364af87adb3377b0e',
      height: 640,
      width: 640
    },
    audio: {}
  },
  {
    name: 'Beautiful People (feat. Khalid)',
    preview: 'https://p.scdn.co/mp3-preview/3ad904af9567a7c7df7d23a8d6700296ded34b4f?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
    popularity: 76,
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
        },
        href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
        id: '6eUKZXaKkcviH0Ku9w2n3V',
        name: 'Ed Sheeran',
        type: 'artist',
        uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny'
        },
        href: 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny',
        id: '6LuN9FCkKOj5PcnpouEgny',
        name: 'Khalid',
        type: 'artist',
        uri: 'spotify:artist:6LuN9FCkKOj5PcnpouEgny'
      }
    ],
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
          },
          href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
          id: '6eUKZXaKkcviH0Ku9w2n3V',
          name: 'Ed Sheeran',
          type: 'artist',
          uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MV',
        'MW',
        'MX',
        'MY',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZW'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/3oIFxDIo2fwuk4lwCmFZCx'
      },
      href: 'https://api.spotify.com/v1/albums/3oIFxDIo2fwuk4lwCmFZCx',
      id: '3oIFxDIo2fwuk4lwCmFZCx',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27373304ce0653c7758dd94b259',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0273304ce0653c7758dd94b259',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485173304ce0653c7758dd94b259',
          width: 64
        }
      ],
      name: 'No.6 Collaborations Project',
      release_date: '2019-07-12',
      release_date_precision: 'day',
      total_tracks: 15,
      type: 'album',
      uri: 'spotify:album:3oIFxDIo2fwuk4lwCmFZCx'
    },
    image: {
      url: 'https://i.scdn.co/image/ab67616d0000b27373304ce0653c7758dd94b259',
      height: 640,
      width: 640
    },
    audio: {}
  },
  {
    name: 'I Don\'t Want Your Money (feat. H.E.R.)',
    preview: 'https://p.scdn.co/mp3-preview/771673209a00f07a3dd75cef40041e8074e7fe2b?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
    popularity: 58,
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
        },
        href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
        id: '6eUKZXaKkcviH0Ku9w2n3V',
        name: 'Ed Sheeran',
        type: 'artist',
        uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3Y7RZ31TRPVadSFVy1o8os'
        },
        href: 'https://api.spotify.com/v1/artists/3Y7RZ31TRPVadSFVy1o8os',
        id: '3Y7RZ31TRPVadSFVy1o8os',
        name: 'H.E.R.',
        type: 'artist',
        uri: 'spotify:artist:3Y7RZ31TRPVadSFVy1o8os'
      }
    ],
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
          },
          href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
          id: '6eUKZXaKkcviH0Ku9w2n3V',
          name: 'Ed Sheeran',
          type: 'artist',
          uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
        }
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MD',
        'ME',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MV',
        'MW',
        'MX',
        'MY',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RU',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZW'
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/3oIFxDIo2fwuk4lwCmFZCx'
      },
      href: 'https://api.spotify.com/v1/albums/3oIFxDIo2fwuk4lwCmFZCx',
      id: '3oIFxDIo2fwuk4lwCmFZCx',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27373304ce0653c7758dd94b259',
          width: 640
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0273304ce0653c7758dd94b259',
          width: 300
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485173304ce0653c7758dd94b259',
          width: 64
        }
      ],
      name: 'No.6 Collaborations Project',
      release_date: '2019-07-12',
      release_date_precision: 'day',
      total_tracks: 15,
      type: 'album',
      uri: 'spotify:album:3oIFxDIo2fwuk4lwCmFZCx'
    },
    image: {
      url: 'https://i.scdn.co/image/ab67616d0000b27373304ce0653c7758dd94b259',
      height: 640,
      width: 640
    },
    audio: {}
  },
  // {
  //   name: 'Put It All on Me (feat. Ella Mai)',
  //   preview: 'https://p.scdn.co/mp3-preview/6ab66ae278aeb548557a6f33846c4795251901e2?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
  //   popularity: 62,
  //   artists: [
  //     {
  //       external_urls: {
  //         spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //       },
  //       href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //       id: '6eUKZXaKkcviH0Ku9w2n3V',
  //       name: 'Ed Sheeran',
  //       type: 'artist',
  //       uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //     },
  //     {
  //       external_urls: {
  //         spotify: 'https://open.spotify.com/artist/7HkdQ0gt53LP4zmHsL0nap'
  //       },
  //       href: 'https://api.spotify.com/v1/artists/7HkdQ0gt53LP4zmHsL0nap',
  //       id: '7HkdQ0gt53LP4zmHsL0nap',
  //       name: 'Ella Mai',
  //       type: 'artist',
  //       uri: 'spotify:artist:7HkdQ0gt53LP4zmHsL0nap'
  //     }
  //   ],
  //   album: {
  //     album_type: 'album',
  //     artists: [
  //       {
  //         external_urls: {
  //           spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //         },
  //         href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //         id: '6eUKZXaKkcviH0Ku9w2n3V',
  //         name: 'Ed Sheeran',
  //         type: 'artist',
  //         uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //       }
  //     ],
  //     available_markets: [
  //       'AD',
  //       'AE',
  //       'AG',
  //       'AL',
  //       'AM',
  //       'AR',
  //       'AT',
  //       'AU',
  //       'AZ',
  //       'BA',
  //       'BB',
  //       'BD',
  //       'BE',
  //       'BF',
  //       'BG',
  //       'BH',
  //       'BI',
  //       'BN',
  //       'BO',
  //       'BR',
  //       'BS',
  //       'BT',
  //       'BW',
  //       'BY',
  //       'BZ',
  //       'CA',
  //       'CH',
  //       'CL',
  //       'CM',
  //       'CO',
  //       'CR',
  //       'CV',
  //       'CW',
  //       'CY',
  //       'CZ',
  //       'DE',
  //       'DK',
  //       'DM',
  //       'DO',
  //       'DZ',
  //       'EC',
  //       'EE',
  //       'EG',
  //       'ES',
  //       'FI',
  //       'FJ',
  //       'FM',
  //       'FR',
  //       'GA',
  //       'GB',
  //       'GD',
  //       'GE',
  //       'GH',
  //       'GM',
  //       'GN',
  //       'GQ',
  //       'GR',
  //       'GT',
  //       'GW',
  //       'GY',
  //       'HK',
  //       'HN',
  //       'HR',
  //       'HT',
  //       'HU',
  //       'ID',
  //       'IE',
  //       'IL',
  //       'IN',
  //       'IS',
  //       'IT',
  //       'JM',
  //       'JO',
  //       'JP',
  //       'KE',
  //       'KG',
  //       'KH',
  //       'KI',
  //       'KM',
  //       'KN',
  //       'KR',
  //       'KW',
  //       'KZ',
  //       'LA',
  //       'LB',
  //       'LC',
  //       'LI',
  //       'LK',
  //       'LR',
  //       'LS',
  //       'LT',
  //       'LU',
  //       'LV',
  //       'MA',
  //       'MC',
  //       'MD',
  //       'ME',
  //       'MH',
  //       'MK',
  //       'ML',
  //       'MN',
  //       'MO',
  //       'MR',
  //       'MT',
  //       'MV',
  //       'MW',
  //       'MX',
  //       'MY',
  //       'NA',
  //       'NE',
  //       'NG',
  //       'NI',
  //       'NL',
  //       'NO',
  //       'NP',
  //       'NR',
  //       'NZ',
  //       'OM',
  //       'PA',
  //       'PE',
  //       'PG',
  //       'PH',
  //       'PK',
  //       'PL',
  //       'PS',
  //       'PT',
  //       'PW',
  //       'PY',
  //       'QA',
  //       'RO',
  //       'RS',
  //       'RU',
  //       'RW',
  //       'SA',
  //       'SB',
  //       'SC',
  //       'SE',
  //       'SG',
  //       'SI',
  //       'SK',
  //       'SL',
  //       'SM',
  //       'SN',
  //       'SR',
  //       'ST',
  //       'SV',
  //       'SZ',
  //       'TD',
  //       'TG',
  //       'TH',
  //       'TL',
  //       'TN',
  //       'TO',
  //       'TR',
  //       'TT',
  //       'TV',
  //       'TW',
  //       'TZ',
  //       'UA',
  //       'UG',
  //       'US',
  //       'UY',
  //       'UZ',
  //       'VC',
  //       'VN',
  //       'VU',
  //       'WS',
  //       'XK',
  //       'ZA',
  //       'ZW'
  //     ],
  //     external_urls: {
  //       spotify: 'https://open.spotify.com/album/3oIFxDIo2fwuk4lwCmFZCx'
  //     },
  //     href: 'https://api.spotify.com/v1/albums/3oIFxDIo2fwuk4lwCmFZCx',
  //     id: '3oIFxDIo2fwuk4lwCmFZCx',
  //     images: [
  //       {
  //         height: 640,
  //         url: 'https://i.scdn.co/image/ab67616d0000b27373304ce0653c7758dd94b259',
  //         width: 640
  //       },
  //       {
  //         height: 300,
  //         url: 'https://i.scdn.co/image/ab67616d00001e0273304ce0653c7758dd94b259',
  //         width: 300
  //       },
  //       {
  //         height: 64,
  //         url: 'https://i.scdn.co/image/ab67616d0000485173304ce0653c7758dd94b259',
  //         width: 64
  //       }
  //     ],
  //     name: 'No.6 Collaborations Project',
  //     release_date: '2019-07-12',
  //     release_date_precision: 'day',
  //     total_tracks: 15,
  //     type: 'album',
  //     uri: 'spotify:album:3oIFxDIo2fwuk4lwCmFZCx'
  //   },
  //   image: {
  //     url: 'https://i.scdn.co/image/ab67616d0000b27373304ce0653c7758dd94b259',
  //     height: 640,
  //     width: 640
  //   },
  //   audio: {}
  // },
  // {
  //   name: 'Fireflies',
  //   preview: 'https://p.scdn.co/mp3-preview/88584b6828b463293b839a6bef802f6217692d35?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
  //   popularity: 79,
  //   artists: [
  //     {
  //       external_urls: {
  //         spotify: 'https://open.spotify.com/artist/07QEuhtrNmmZ0zEcqE9SF6'
  //       },
  //       href: 'https://api.spotify.com/v1/artists/07QEuhtrNmmZ0zEcqE9SF6',
  //       id: '07QEuhtrNmmZ0zEcqE9SF6',
  //       name: 'Owl City',
  //       type: 'artist',
  //       uri: 'spotify:artist:07QEuhtrNmmZ0zEcqE9SF6'
  //     }
  //   ],
  //   album: {
  //     album_type: 'album',
  //     artists: [
  //       {
  //         external_urls: {
  //           spotify: 'https://open.spotify.com/artist/07QEuhtrNmmZ0zEcqE9SF6'
  //         },
  //         href: 'https://api.spotify.com/v1/artists/07QEuhtrNmmZ0zEcqE9SF6',
  //         id: '07QEuhtrNmmZ0zEcqE9SF6',
  //         name: 'Owl City',
  //         type: 'artist',
  //         uri: 'spotify:artist:07QEuhtrNmmZ0zEcqE9SF6'
  //       }
  //     ],
  //     available_markets: [
  //       'AD',
  //       'AE',
  //       'AG',
  //       'AL',
  //       'AM',
  //       'AR',
  //       'AT',
  //       'AU',
  //       'AZ',
  //       'BA',
  //       'BB',
  //       'BD',
  //       'BE',
  //       'BF',
  //       'BG',
  //       'BH',
  //       'BI',
  //       'BN',
  //       'BO',
  //       'BR',
  //       'BS',
  //       'BT',
  //       'BW',
  //       'BY',
  //       'BZ',
  //       'CA',
  //       'CH',
  //       'CL',
  //       'CM',
  //       'CO',
  //       'CR',
  //       'CV',
  //       'CY',
  //       'CZ',
  //       'DE',
  //       'DK',
  //       'DM',
  //       'DO',
  //       'EC',
  //       'EE',
  //       'EG',
  //       'ES',
  //       'FI',
  //       'FJ',
  //       'FM',
  //       'FR',
  //       'GA',
  //       'GB',
  //       'GD',
  //       'GH',
  //       'GM',
  //       'GN',
  //       'GQ',
  //       'GR',
  //       'GT',
  //       'GW',
  //       'GY',
  //       'HK',
  //       'HN',
  //       'HR',
  //       'HT',
  //       'HU',
  //       'ID',
  //       'IE',
  //       'IL',
  //       'IN',
  //       'IS',
  //       'IT',
  //       'JM',
  //       'JO',
  //       'JP',
  //       'KE',
  //       'KG',
  //       'KH',
  //       'KI',
  //       'KM',
  //       'KN',
  //       'KR',
  //       'KW',
  //       'KZ',
  //       'LA',
  //       'LB',
  //       'LC',
  //       'LI',
  //       'LK',
  //       'LR',
  //       'LS',
  //       'LT',
  //       'LU',
  //       'LV',
  //       'MC',
  //       'MD',
  //       'ME',
  //       'MH',
  //       'MK',
  //       'ML',
  //       'MN',
  //       'MO',
  //       'MR',
  //       'MT',
  //       'MV',
  //       'MW',
  //       'MX',
  //       'MY',
  //       'NA',
  //       'NE',
  //       'NG',
  //       'NI',
  //       'NL',
  //       'NO',
  //       'NP',
  //       'NR',
  //       'NZ',
  //       'OM',
  //       'PA',
  //       'PE',
  //       'PG',
  //       'PH',
  //       'PK',
  //       'PL',
  //       'PS',
  //       'PT',
  //       'PW',
  //       'PY',
  //       'QA',
  //       'RO',
  //       'RS',
  //       'RU',
  //       'RW',
  //       'SA',
  //       'SB',
  //       'SC',
  //       'SE',
  //       'SG',
  //       'SI',
  //       'SK',
  //       'SL',
  //       'SN',
  //       'SR',
  //       'ST',
  //       'SV',
  //       'SZ',
  //       'TD',
  //       'TG',
  //       'TH',
  //       'TL',
  //       'TN',
  //       'TO',
  //       'TR',
  //       'TT',
  //       'TV',
  //       'TW',
  //       'TZ',
  //       'UA',
  //       'UG',
  //       'US',
  //       'UY',
  //       'UZ',
  //       'VC',
  //       'VN',
  //       'WS',
  //       'XK',
  //       'ZA',
  //       'ZW'
  //     ],
  //     external_urls: {
  //       spotify: 'https://open.spotify.com/album/3vf65wfk1EEjVhy6BjENsS'
  //     },
  //     href: 'https://api.spotify.com/v1/albums/3vf65wfk1EEjVhy6BjENsS',
  //     id: '3vf65wfk1EEjVhy6BjENsS',
  //     images: [
  //       {
  //         height: 640,
  //         url: 'https://i.scdn.co/image/ab67616d0000b273785d4e702802da500fc78b32',
  //         width: 640
  //       },
  //       {
  //         height: 300,
  //         url: 'https://i.scdn.co/image/ab67616d00001e02785d4e702802da500fc78b32',
  //         width: 300
  //       },
  //       {
  //         height: 64,
  //         url: 'https://i.scdn.co/image/ab67616d00004851785d4e702802da500fc78b32',
  //         width: 64
  //       }
  //     ],
  //     name: 'Ocean Eyes',
  //     release_date: '2009-01-01',
  //     release_date_precision: 'day',
  //     total_tracks: 12,
  //     type: 'album',
  //     uri: 'spotify:album:3vf65wfk1EEjVhy6BjENsS'
  //   },
  //   image: {
  //     url: 'https://i.scdn.co/image/ab67616d0000b273785d4e702802da500fc78b32',
  //     height: 640,
  //     width: 640
  //   },
  //   audio: {}
  // },
  // {
  //   name: 'Afterglow',
  //   preview: 'https://p.scdn.co/mp3-preview/ca59ce0946d37f9a7da3ab12b29a2f8a3605d50a?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
  //   popularity: 88,
  //   artists: [
  //     {
  //       external_urls: {
  //         spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //       },
  //       href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //       id: '6eUKZXaKkcviH0Ku9w2n3V',
  //       name: 'Ed Sheeran',
  //       type: 'artist',
  //       uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //     }
  //   ],
  //   album: {
  //     album_type: 'single',
  //     artists: [
  //       {
  //         external_urls: {
  //           spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //         },
  //         href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //         id: '6eUKZXaKkcviH0Ku9w2n3V',
  //         name: 'Ed Sheeran',
  //         type: 'artist',
  //         uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //       }
  //     ],
  //     available_markets: [
  //       'AD',
  //       'AE',
  //       'AG',
  //       'AL',
  //       'AM',
  //       'AR',
  //       'AT',
  //       'AU',
  //       'AZ',
  //       'BA',
  //       'BB',
  //       'BD',
  //       'BE',
  //       'BF',
  //       'BG',
  //       'BH',
  //       'BI',
  //       'BN',
  //       'BO',
  //       'BR',
  //       'BS',
  //       'BT',
  //       'BW',
  //       'BY',
  //       'BZ',
  //       'CA',
  //       'CH',
  //       'CL',
  //       'CM',
  //       'CO',
  //       'CR',
  //       'CV',
  //       'CW',
  //       'CY',
  //       'CZ',
  //       'DE',
  //       'DK',
  //       'DM',
  //       'DO',
  //       'DZ',
  //       'EC',
  //       'EE',
  //       'EG',
  //       'ES',
  //       'FI',
  //       'FJ',
  //       'FM',
  //       'FR',
  //       'GA',
  //       'GB',
  //       'GD',
  //       'GE',
  //       'GH',
  //       'GM',
  //       'GN',
  //       'GQ',
  //       'GR',
  //       'GT',
  //       'GW',
  //       'GY',
  //       'HK',
  //       'HN',
  //       'HR',
  //       'HT',
  //       'HU',
  //       'ID',
  //       'IE',
  //       'IL',
  //       'IN',
  //       'IS',
  //       'IT',
  //       'JM',
  //       'JO',
  //       'JP',
  //       'KE',
  //       'KG',
  //       'KH',
  //       'KI',
  //       'KM',
  //       'KN',
  //       'KR',
  //       'KW',
  //       'KZ',
  //       'LA',
  //       'LB',
  //       'LC',
  //       'LI',
  //       'LK',
  //       'LR',
  //       'LS',
  //       'LT',
  //       'LU',
  //       'LV',
  //       'MA',
  //       'MC',
  //       'MD',
  //       'ME',
  //       'MH',
  //       'MK',
  //       'ML',
  //       'MN',
  //       'MO',
  //       'MR',
  //       'MT',
  //       'MV',
  //       'MW',
  //       'MX',
  //       'MY',
  //       'NA',
  //       'NE',
  //       'NG',
  //       'NI',
  //       'NL',
  //       'NO',
  //       'NP',
  //       'NR',
  //       'NZ',
  //       'OM',
  //       'PA',
  //       'PE',
  //       'PG',
  //       'PH',
  //       'PK',
  //       'PL',
  //       'PS',
  //       'PT',
  //       'PW',
  //       'PY',
  //       'QA',
  //       'RO',
  //       'RS',
  //       'RU',
  //       'RW',
  //       'SA',
  //       'SB',
  //       'SC',
  //       'SE',
  //       'SG',
  //       'SI',
  //       'SK',
  //       'SL',
  //       'SM',
  //       'SN',
  //       'SR',
  //       'ST',
  //       'SV',
  //       'SZ',
  //       'TD',
  //       'TG',
  //       'TH',
  //       'TL',
  //       'TN',
  //       'TO',
  //       'TR',
  //       'TT',
  //       'TV',
  //       'TW',
  //       'TZ',
  //       'UA',
  //       'UG',
  //       'US',
  //       'UY',
  //       'UZ',
  //       'VC',
  //       'VN',
  //       'VU',
  //       'WS',
  //       'XK',
  //       'ZA',
  //       'ZW'
  //     ],
  //     external_urls: {
  //       spotify: 'https://open.spotify.com/album/5bb2Sf8jps2DTyI2urMThV'
  //     },
  //     href: 'https://api.spotify.com/v1/albums/5bb2Sf8jps2DTyI2urMThV',
  //     id: '5bb2Sf8jps2DTyI2urMThV',
  //     images: [
  //       {
  //         height: 640,
  //         url: 'https://i.scdn.co/image/ab67616d0000b27388e170d5ced543d191593fc8',
  //         width: 640
  //       },
  //       {
  //         height: 300,
  //         url: 'https://i.scdn.co/image/ab67616d00001e0288e170d5ced543d191593fc8',
  //         width: 300
  //       },
  //       {
  //         height: 64,
  //         url: 'https://i.scdn.co/image/ab67616d0000485188e170d5ced543d191593fc8',
  //         width: 64
  //       }
  //     ],
  //     name: 'Afterglow',
  //     release_date: '2020-12-21',
  //     release_date_precision: 'day',
  //     total_tracks: 1,
  //     type: 'album',
  //     uri: 'spotify:album:5bb2Sf8jps2DTyI2urMThV'
  //   },
  //   image: {
  //     url: 'https://i.scdn.co/image/ab67616d0000b27388e170d5ced543d191593fc8',
  //     height: 640,
  //     width: 640
  //   },
  //   audio: {}
  // },
  // {
  //   name: 'Nina',
  //   preview: 'https://p.scdn.co/mp3-preview/24394ca5326534211e8c1976f1769850c9d05161?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
  //   popularity: 58,
  //   artists: [
  //     {
  //       external_urls: {
  //         spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //       },
  //       href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //       id: '6eUKZXaKkcviH0Ku9w2n3V',
  //       name: 'Ed Sheeran',
  //       type: 'artist',
  //       uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //     }
  //   ],
  //   album: {
  //     album_type: 'album',
  //     artists: [
  //       {
  //         external_urls: {
  //           spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //         },
  //         href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //         id: '6eUKZXaKkcviH0Ku9w2n3V',
  //         name: 'Ed Sheeran',
  //         type: 'artist',
  //         uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //       }
  //     ],
  //     available_markets: [
  //       'AE',
  //       'AG',
  //       'AL',
  //       'AM',
  //       'AR',
  //       'AT',
  //       'AU',
  //       'AZ',
  //       'BA',
  //       'BB',
  //       'BE',
  //       'BF',
  //       'BG',
  //       'BH',
  //       'BI',
  //       'BN',
  //       'BO',
  //       'BR',
  //       'BS',
  //       'BW',
  //       'BY',
  //       'BZ',
  //       'CA',
  //       'CH',
  //       'CL',
  //       'CM',
  //       'CO',
  //       'CR',
  //       'CV',
  //       'CY',
  //       'CZ',
  //       'DE',
  //       'DK',
  //       'DM',
  //       'DO',
  //       'DZ',
  //       'EC',
  //       'EE',
  //       'EG',
  //       'ES',
  //       'FI',
  //       'FJ',
  //       'FM',
  //       'FR',
  //       'GA',
  //       'GB',
  //       'GD',
  //       'GH',
  //       'GM',
  //       'GN',
  //       'GQ',
  //       'GR',
  //       'GT',
  //       'GW',
  //       'HK',
  //       'HN',
  //       'HR',
  //       'HT',
  //       'HU',
  //       'ID',
  //       'IE',
  //       'IL',
  //       'IN',
  //       'IT',
  //       'JM',
  //       'JO',
  //       'JP',
  //       'KE',
  //       'KG',
  //       'KH',
  //       'KM',
  //       'KN',
  //       'KR',
  //       'KW',
  //       'KZ',
  //       'LA',
  //       'LB',
  //       'LC',
  //       'LK',
  //       'LR',
  //       'LS',
  //       'LT',
  //       'LU',
  //       'LV',
  //       'MA',
  //       'MD',
  //       'ME',
  //       'MK',
  //       'ML',
  //       'MN',
  //       'MO',
  //       'MR',
  //       'MT',
  //       'MW',
  //       'MX',
  //       'MY',
  //       'NA',
  //       'NE',
  //       'NG',
  //       'NI',
  //       'NL',
  //       'NO',
  //       'NP',
  //       'NZ',
  //       'OM',
  //       'PA',
  //       'PE',
  //       'PG',
  //       'PH',
  //       'PL',
  //       'PT',
  //       'PY',
  //       'QA',
  //       'RO',
  //       'RS',
  //       'RU',
  //       'RW',
  //       'SA',
  //       'SC',
  //       'SE',
  //       'SG',
  //       'SI',
  //       'SK',
  //       'SL',
  //       'SN',
  //       'ST',
  //       'SV',
  //       'SZ',
  //       'TD',
  //       'TG',
  //       'TH',
  //       'TL',
  //       'TN',
  //       'TR',
  //       'TT',
  //       'TW',
  //       'TZ',
  //       'UA',
  //       'UG',
  //       'US',
  //       'UY',
  //       'UZ',
  //       'VC',
  //       'VN',
  //       'XK',
  //       'ZA',
  //       'ZW'
  //     ],
  //     external_urls: {
  //       spotify: 'https://open.spotify.com/album/1xn54DMo2qIqBuMqHtUsFd'
  //     },
  //     href: 'https://api.spotify.com/v1/albums/1xn54DMo2qIqBuMqHtUsFd',
  //     id: '1xn54DMo2qIqBuMqHtUsFd',
  //     images: [
  //       {
  //         height: 640,
  //         url: 'https://i.scdn.co/image/ab67616d0000b27313b3e37318a0c247b550bccd',
  //         width: 640
  //       },
  //       {
  //         height: 300,
  //         url: 'https://i.scdn.co/image/ab67616d00001e0213b3e37318a0c247b550bccd',
  //         width: 300
  //       },
  //       {
  //         height: 64,
  //         url: 'https://i.scdn.co/image/ab67616d0000485113b3e37318a0c247b550bccd',
  //         width: 64
  //       }
  //     ],
  //     name: 'x (Deluxe Edition)',
  //     release_date: '2014-06-21',
  //     release_date_precision: 'day',
  //     total_tracks: 16,
  //     type: 'album',
  //     uri: 'spotify:album:1xn54DMo2qIqBuMqHtUsFd'
  //   },
  //   image: {
  //     url: 'https://i.scdn.co/image/ab67616d0000b27313b3e37318a0c247b550bccd',
  //     height: 640,
  //     width: 640
  //   },
  //   audio: {}
  // },
  // {
  //   name: 'You Need Me, I Don\'t Need You',
  //   preview: 'https://p.scdn.co/mp3-preview/7434e891c3f1427caad1e22617df7e81b82dc0b7?cid=e668b7765ffb4c0b84be159d1a2f7a9a',
  //   popularity: 64,
  //   artists: [
  //     {
  //       external_urls: {
  //         spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //       },
  //       href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //       id: '6eUKZXaKkcviH0Ku9w2n3V',
  //       name: 'Ed Sheeran',
  //       type: 'artist',
  //       uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //     }
  //   ],
  //   album: {
  //     album_type: 'album',
  //     artists: [
  //       {
  //         external_urls: {
  //           spotify: 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'
  //         },
  //         href: 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V',
  //         id: '6eUKZXaKkcviH0Ku9w2n3V',
  //         name: 'Ed Sheeran',
  //         type: 'artist',
  //         uri: 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'
  //       }
  //     ],
  //     available_markets: [
  //       'AD',
  //       'AE',
  //       'AG',
  //       'AL',
  //       'AM',
  //       'AR',
  //       'AT',
  //       'AU',
  //       'AZ',
  //       'BA',
  //       'BB',
  //       'BD',
  //       'BE',
  //       'BF',
  //       'BG',
  //       'BH',
  //       'BI',
  //       'BN',
  //       'BO',
  //       'BR',
  //       'BS',
  //       'BT',
  //       'BW',
  //       'BY',
  //       'BZ',
  //       'CH',
  //       'CL',
  //       'CM',
  //       'CO',
  //       'CR',
  //       'CV',
  //       'CW',
  //       'CY',
  //       'CZ',
  //       'DE',
  //       'DK',
  //       'DM',
  //       'DO',
  //       'DZ',
  //       'EC',
  //       'EE',
  //       'EG',
  //       'ES',
  //       'FI',
  //       'FJ',
  //       'FM',
  //       'FR',
  //       'GA',
  //       'GB',
  //       'GD',
  //       'GE',
  //       'GH',
  //       'GM',
  //       'GN',
  //       'GQ',
  //       'GR',
  //       'GT',
  //       'GW',
  //       'GY',
  //       'HK',
  //       'HN',
  //       'HR',
  //       'HT',
  //       'HU',
  //       'ID',
  //       'IE',
  //       'IL',
  //       'IN',
  //       'IS',
  //       'IT',
  //       'JM',
  //       'JO',
  //       'KE',
  //       'KG',
  //       'KH',
  //       'KI',
  //       'KM',
  //       'KN',
  //       'KR',
  //       'KW',
  //       'KZ',
  //       'LA',
  //       'LB',
  //       'LC',
  //       'LI',
  //       'LK',
  //       'LR',
  //       'LS',
  //       'LT',
  //       'LU',
  //       'LV',
  //       'MA',
  //       'MC',
  //       'MD',
  //       'ME',
  //       'MH',
  //       'MK',
  //       'ML',
  //       'MN',
  //       'MO',
  //       'MR',
  //       'MT',
  //       'MV',
  //       'MW',
  //       'MX',
  //       'MY',
  //       'NA',
  //       'NE',
  //       'NG',
  //       'NI',
  //       'NL',
  //       'NO',
  //       'NP',
  //       'NR',
  //       'NZ',
  //       'OM',
  //       'PA',
  //       'PE',
  //       'PG',
  //       'PH',
  //       'PK',
  //       'PL',
  //       'PS',
  //       'PT',
  //       'PW',
  //       'PY',
  //       'QA',
  //       'RO',
  //       'RS',
  //       'RU',
  //       'RW',
  //       'SA',
  //       'SB',
  //       'SC',
  //       'SE',
  //       'SG',
  //       'SI',
  //       'SK',
  //       'SL',
  //       'SM',
  //       'SN',
  //       'SR',
  //       'ST',
  //       'SV',
  //       'SZ',
  //       'TD',
  //       'TG',
  //       'TH',
  //       'TL',
  //       'TN',
  //       'TO',
  //       'TR',
  //       'TT',
  //       'TV',
  //       'TW',
  //       'TZ',
  //       'UA',
  //       'UG',
  //       'US',
  //       'UY',
  //       'UZ',
  //       'VC',
  //       'VN',
  //       'VU',
  //       'WS',
  //       'XK',
  //       'ZA',
  //       'ZW'
  //     ],
  //     external_urls: {
  //       spotify: 'https://open.spotify.com/album/02pi98kE0nra0yBqCStzbC'
  //     },
  //     href: 'https://api.spotify.com/v1/albums/02pi98kE0nra0yBqCStzbC',
  //     id: '02pi98kE0nra0yBqCStzbC',
  //     images: [
  //       {
  //         height: 640,
  //         url: 'https://i.scdn.co/image/ab67616d0000b273ed139c2e0e3681cc2d35e256',
  //         width: 640
  //       },
  //       {
  //         height: 300,
  //         url: 'https://i.scdn.co/image/ab67616d00001e02ed139c2e0e3681cc2d35e256',
  //         width: 300
  //       },
  //       {
  //         height: 64,
  //         url: 'https://i.scdn.co/image/ab67616d00004851ed139c2e0e3681cc2d35e256',
  //         width: 64
  //       }
  //     ],
  //     name: '+',
  //     release_date: '2011-09-09',
  //     release_date_precision: 'day',
  //     total_tracks: 16,
  //     type: 'album',
  //     uri: 'spotify:album:02pi98kE0nra0yBqCStzbC'
  //   },
  //   image: {
  //     url: 'https://i.scdn.co/image/ab67616d0000b273ed139c2e0e3681cc2d35e256',
  //     height: 640,
  //     width: 640
  //   },
  //   audio: {}
  // }
].map(track => new Track(track));

mockPlaylist = new Playlist(mockPlaylistData);
